### ISSUE TITLE
[Question] Lag between current offset and log end offset

### ISSUE THREAD

**Issue by pinkyrathore** [EnMasseProject/amqp-kafka-bridge#49] opened 2017-03-24 14:03 UTC
Is the lag between current offset and log end offset expected as a result of https://github.com/EnMasseProject/amqp-kafka-bridge/issues/23

E.g. Before creating a bridge receiver, the offset state on a topic is - 
current offset = 24 
log end offset = 24

After connecting to bridge, when a new message is consumed from topic and successfully delivered, the offset state is -
current offset = 24
log end offset = 25

**Comment by ppatierno** [comment] 2017-03-25 15:05
Hi,
can you explain me better your scenario and a way to reproduce it. I'd like to dig into it better.
When you say "a new message is consumed from topic" are you talking to consume it using an AMQP receiver attached to the bridge or a native Kafka receiver attached directly to the topic ?

**Comment by pinkyrathore** [comment] 2017-03-27 08:32
Hi,
When I say "a new message is consumed", it is consumed using an AMQP receiver attached to the bridge.

Today, I ran two scenarios with newly created kafka topics. Below are steps to reproduce it.

**Scenario 1** (Consume message using AMQP receiver attached to the bridge) -

1. Create a new topic with name "topic_bridge"
bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic topic_bridge

2. Start the bridge 
java -jar target/amqp-kafka-bridge-1.0-SNAPSHOT.jar

3. In enmasse.kafka.bridge.example.BridgeReceiver.java, update the topic and consumer group name -
TOPIC = topic_bridge
GROUP_ID_PREFIX = topic_bridge_consumer_group_1

4. Run BridgeReceiver.java
output says "Connected as vert.x-f4189ddf-70b5-4dc5-b43c-2a7c1d6fb59b"

5. Check initial state of offset in topic
./bin/kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --describe --group topic_bridge_consumer_group_1

output > PARTITION = 0, CURRENT-OFFSET = unknown, LOG-END-OFFSET = 0, LAG = unknown

5. Start a producer and add a message
bin/kafka-console-producer.sh --broker-list localhost:9092 --topic topic_bridge
message 1

6. Check state of offset
./bin/kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --describe --group topic_bridge_consumer_group_1

output > PARTITION = 0, CURRENT-OFFSET = 0, LOG-END-OFFSET = 1, LAG = 1

In this scenario, every time Bridge receiver is re-started after step 6, the last message is re-delivered.
Even when more messages are produced and then consumed by amqp bridge receiver, the LAG is always equal to 1.

**Scenario 2** (Consume message using a kafka consumer directly listening to topic e.g. kafka-console-consumer.sh)

1. Create a new topic with name "topic_test_consumer"
bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic topic_test_consumer

2. Start a consumer 
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic_test_consumer --from-beginning --consumer.config config/consumer_1.properties

5. Check initial state of offset in topic
./bin/kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --describe --group topic_test_consumer_group_1

output > PARTITION = 0, CURRENT-OFFSET = 0, LOG-END-OFFSET = 0, LAG = 0

5. Start a producer and add a message
bin/kafka-console-producer.sh --broker-list localhost:9092 --topic topic_test_consumer
message 1

6. Check offset
./bin/kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9092 --describe --group topic_test_consumer_group_1

output > PARTITION = 0, CURRENT-OFFSET = 1, LOG-END-OFFSET = 1, LAG = 0

If we look at initial value of current-offset in both scenarios - It is "unknown" in scenario 1 and 0 in scenario 2

So, I was wondering if the lag in scenario 1 is due to the offsets being managed / committed by the bridge.

**Comment by ppatierno** [comment] 2017-03-27 12:47
In the scenario 1, attaching an AMQP receiver just creates a native Kafka consumer on the topic so it should fall into the scenario 2. I'll dig into it and come back to you, thanks for reporting !

**Comment by ppatierno** [comment] 2017-03-28 14:47
@pinkyrathore I can reproduce the issue and it seems to be related to the "auto commit" that is DISABLED and not configurable in the bridge but is ENABLED by default in the kafka-console-consumer.
The bridge needs "auto commit" DISABLED because the offset needs to be committed only when the AMQP receiver settles the message as well. Having "auto commit" DISABLED starts in the situation of current offset is unknown (so lag is as well). Have you tried with a simple application using the native Kafka client with "auto commit" DISABLED ?

**Comment by ppatierno** [comment] 2017-03-28 15:21
@pinkyrathore the AMQP receiver connects using the AT_LEAST_ONCE QoS level as default and it means that the Kafka consumer part in the bridge executes a call to commitSync with the "current offset" of the consumed message. It's wrong because it should be "current offset" + 1 avoiding on restart to have the receiver getting always last message. If you try to use the AMQP receiver with AT_MOST_ONCE QoS level (this.receivers[i].setQoS(ProtonQoS.AT_MOST_ONCE); to add just before the this.receivers[i].handler ....) you can see that after consuming the message the LAG is 0 (even if the starting situation is "unknown" but as I said it seems to depend on using the auto commit DISABLED). In this case the LAG is 0 because the Kafka consumer part in the bridge use the commitSync() method (with no offsets as parameters) and it seems that this method set the offset to the right value internallu "current offset" + 1.
Does it make sense to you ?
I have to fix committing offset adding the + 1 as well as explained in the Kafka API documentation : 

> Note: The committed offset should always be the offset of the next message that your application will read. Thus, when calling commitSync(offsets) you should add one to the offset of the last message processed.

**Comment by pinkyrathore** [comment] 2017-03-30 06:08
@ppatierno yes, this makes sense. Thanks for looking into this.

**Comment by ppatierno** [comment] 2017-03-30 13:58
I'm going to close this on behalf of 2d5ba0799b7dee27c35999707240d5ae25e3c79f

**Closed by ppatierno** 2017-03-30 13:58 UTC
